### ISSUE TITLE
What are hardware requirements?

### ISSUE THREAD

**Issue by matkoniecz** [Zverik/editor-stats#4]
> Download a changeset bz2 file from planet.osm.org.

I want to play around with this statics analyser (and maybe implement ideas from #2) but I am unsure about order of magnitude of hardware resources.

It looks like it is reading file without need for database imports etc so maybe there is a hope that it will run on a laptop with 4GB RAM and 256GB SSD?

**Comment by Zverik** [comment]
It processes a file line-by-line, so it does not have any requirements toward either memory or disk.

**Comment by Zverik** [comment]
To add to this, all you need is ~500 MB of disk space to store a gzipped changeset csv. Of course you can skip even that by piping the downloaded file directly to a perl script.
