### ISSUE TITLE
raw data?

### ISSUE THREAD

**Issue by matkoniecz** [Zverik/editor-stats#6]
https://wiki.openstreetmap.org/wiki/Editor_usage_stats is very interesting, unfortunately graphs are outdated

Is it possible to publish somewhere ( http://gist.github.com/ ? ) raw data? (if not then I will convert tables back in raw numbers but if you have this data available...)

**Comment by Zverik** [comment]
I usually update the data once every three months. What really matters are the full year numbers, so it's safe to wait until January. If you want, I can update it soon.

**Comment by Zverik** [comment]
The data has been updated in March, with another update coming up this Summer.
