### ISSUE TITLE
OSM2go does not show up

### ISSUE THREAD

**Issue by DerDakon** [Zverik/editor-stats#7]
Even if I see some mentions of [OSM2go](https://github.com/osm2go/osm2go) in the scripts, it does not show up in the end results. Is that just a threshold thing or a script bug? I can live with the former, but not with the latter ;)

**Comment by Zverik** [comment]
I've tested the script, and osm2go is picked up — but there are too few changesets for it to be featured in the tables. You need ~50-80 users a year to get into these.

**Comment by DerDakon** [comment]
ok, that makes sense.
