### ISSUE TITLE
Can not run script stats.pl

### ISSUE THREAD

**Issue by Binnette** [Zverik/editor-stats#8]
Hi @Zverik, i'm a noob in perl and i can not get the stats.pl script to work on ubuntu.

Here is the error i got:

```bash
$ gzip -dc changesets.csv.gz | ./stats.pl 2015 > 2015.lst
Can't locate EDetect.pm in @INC (you may need to install the EDetect module)
(@INC contains: ~/perl5/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi ~/perl5/lib/perl5/5.30.0 ~/perl5/lib/perl5/x86_64-linux-gnu-thread-multi ~/perl5/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./stats.pl line 4.
BEGIN failed--compilation aborted at ./stats.pl line 4.
```
I read many article how to install perl module. but i can't install your local EDetect.pm module

**Comment by Binnette** [comment]
Ok, so i decided just to copy manually your pm file into ~/perl5/lib/perl5/5.30.0/

Is there a better solution? Can you please add this solution in the readme file?

Thank you and have a nice day :+1:

**Comment by Binnette** [comment]
Ok i really can not get it to work. I get the following error:
`Use of uninitialized value in substr at ./stats.pl line 28, <> line 1.`

**Comment by Zverik** [comment]
Hi Binnette, I've just updated all scripts, adding `EDetect` to the library path. Not sure how you get the "uninitialized value" error: could you show the result of `gzip -dc changesets.csv.gz | head -n 2` here?

**Comment by Binnette** [comment]
Hi @Zverik, I finally get it to work. :+1: 

I don't understand how. But after rebooting my PC, script.pl works nicely without any error. May be I've done something wrong.

Thanks for your support, I now can update the wiki page [Editor stats](https://wiki.openstreetmap.org/wiki/Editor_usage_stats) when needed :wink: 

Thank again and have a nice day :+1:
